import type { Deal, DealNote, Task } from "./types";

const now = new Date().toISOString();

export const seedTasks: Task[] = [
  {
    id: "pre-transaction-documents",
    serialNumber: "A1",
    phase: "Pre-Execution Items",
    timeline: "Prior to X",
    action: "Transaction documents to be finalised, including Shareholders' Agreement, Subscription Agreement, Employment Agreement and ancillary documents.",
    parties: ["Company", "Founders", "FIRM", "Investor"],
    comments: "-",
    status: "In Progress",
    priority: "Critical",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Agreed-form transaction documents" },
    riskCategory: "Closing blocker",
    dependencies: [],
    owner: "Deal Associate",
    reviewer: "Partner",
    lastUpdated: now,
    notes: "Track SHA, SSA, disclosure letter and ancillary agreements as separate documents in the evidence room if needed.",
    sourceReference: "Master Checklist row A1",
    documentCategory: "Transaction Documents",
    documentStatus: "Under Review",
    agreedFormRequired: true,
    mandatoryForClosing: true
  },
  {
    id: "pre-stamp-papers",
    serialNumber: "A2",
    phase: "Pre-Execution Items",
    timeline: "Prior to X",
    action: "Stamp papers to be procured before execution.",
    parties: ["Company", "FIRM"],
    comments: "FIRM will provide relevant stamp duty procurement details closer to execution.",
    status: "Not Started",
    priority: "High",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Stamp paper procurement proof" },
    riskCategory: "Legal validity risk",
    dependencies: [{ taskId: "pre-transaction-documents", label: "Documents must be near final before stamping" }],
    owner: "Company CS",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row A2",
    documentCategory: "Transaction Documents",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "pre-disclosure-letter",
    serialNumber: "A3",
    phase: "Pre-Execution Items",
    timeline: "Prior to X",
    action: "Disclosure letter to be finalised.",
    parties: ["Company", "Founders", "FIRM"],
    comments: "To be circulated by Company for FIRM review.",
    status: "With Client",
    priority: "High",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Final disclosure letter" },
    riskCategory: "Investor protection risk",
    dependencies: [{ taskId: "pre-transaction-documents", label: "Disclosure letter tied to transaction documents" }],
    owner: "Company Counsel",
    reviewer: "Investor Counsel",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row A3",
    documentCategory: "Transaction Documents",
    documentStatus: "Draft Shared",
    agreedFormRequired: true,
    mandatoryForClosing: true
  },
  {
    id: "cp-due-diligence",
    serialNumber: "B1",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Completion of financial, business and legal due diligence, management background and reference checks, and resolution of diligence issues.",
    parties: ["Company", "Founders", "Investor", "FIRM"],
    comments: "-",
    status: "Under Review",
    priority: "High",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Diligence closure tracker / issue resolution evidence" },
    riskCategory: "Investor protection risk",
    dependencies: [],
    owner: "Diligence Lead",
    reviewer: "Partner",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row B1",
    documentCategory: "Post-closing Evidence",
    documentStatus: "Under Review",
    mandatoryForClosing: true
  },
  {
    id: "cp-third-party-consents",
    serialNumber: "B2",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Obtain third-party consents required for the fundraise and related transactions, if applicable.",
    parties: ["Company", "Founders"],
    comments: "-",
    status: "Not Started",
    priority: "Medium",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Third-party consent copies or N/A confirmation" },
    riskCategory: "Legal validity risk",
    dependencies: [],
    owner: "Company Legal",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row B2",
    documentCategory: "Corporate Approvals",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "cp-valuation-certificate",
    serialNumber: "B3",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Procure valuation support for the issue price, including Registered Valuer report for Companies Act preferential allotment and FEMA pricing certificate from CA / merchant banker / cost accountant, as applicable.",
    parties: ["Registered Valuer", "Independent CA / Merchant Banker", "Company", "FIRM"],
    comments: "Company to share draft valuation materials with FIRM for review and then provide signed versions. Report should be dated 30 days prior to EGM for issuance approval. Income-tax angel-tax analysis should be treated as legacy/DD context and confirmed for current applicability.",
    status: "In Progress",
    priority: "Critical",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Signed valuation report / FEMA pricing certificate register link" },
    riskCategory: "Closing blocker",
    dependencies: [],
    owner: "Company Finance",
    reviewer: "Partner",
    lastUpdated: now,
    notes: "Critical CP. Track freshness of the valuation materials and re-confirm if stale.",
    sourceReference: "Master Checklist row B3; legal update L2/L8 in PLAN.md",
    documentCategory: "Valuation",
    documentStatus: "Under Review",
    statutoryDeadlineNote: "Soft freshness check before EGM",
    mandatoryForClosing: true
  },
  {
    id: "cp-board-notice-issuance",
    serialNumber: "B4",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Issue notice of board meeting for transaction document approval, bank account, ESOP pool, capital changes, consents, private placement offer approval and EGM call.",
    parties: ["Company", "Founders", "FIRM"],
    comments: "FIRM to provide templates. Company to circulate draft board resolution extracts for review and share executed copies once confirmed.",
    status: "Not Started",
    priority: "High",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Board notice and draft resolutions" },
    riskCategory: "Legal validity risk",
    dependencies: [{ taskId: "cp-valuation-certificate", label: "Valuation certificate supports issuance approval" }],
    owner: "Company CS",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row B4",
    documentCategory: "Corporate Approvals",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "cp-board-approval",
    serialNumber: "B5",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Hold board meeting for approval of the items in B4.",
    parties: ["Company", "Founders"],
    comments: "-",
    status: "Not Started",
    priority: "Critical",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Executed board resolution extracts" },
    riskCategory: "Closing blocker",
    dependencies: [{ taskId: "cp-board-notice-issuance", label: "Board notice precedes board meeting" }],
    owner: "Company CS",
    reviewer: "Partner",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row B5",
    documentCategory: "Corporate Approvals",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "cp-egm-notice",
    serialNumber: "B6",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Issue EGM notice for increase/reclassification of authorised share capital and private placement issuance approval.",
    parties: ["Company", "Founders", "FIRM"],
    comments: "FIRM to provide templates. Draft EGM notice to be circulated by Company for review.",
    status: "Not Started",
    priority: "High",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "EGM notice and draft shareholder resolutions" },
    riskCategory: "Legal validity risk",
    dependencies: [{ taskId: "cp-board-approval", label: "Board approval before EGM notice" }],
    owner: "Company CS",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row B6",
    documentCategory: "Corporate Approvals",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "cp-egm-approval",
    serialNumber: "B7",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Hold EGM for approval of the items in B6.",
    parties: ["Company", "Founders"],
    comments: "-",
    status: "Not Started",
    priority: "Critical",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Executed EGM resolution extracts" },
    riskCategory: "Closing blocker",
    dependencies: [{ taskId: "cp-egm-notice", label: "EGM notice precedes EGM" }],
    owner: "Company CS",
    reviewer: "Partner",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row B7",
    documentCategory: "Corporate Approvals",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "cp-sh7-mgt14",
    serialNumber: "B8",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "File e-form SH-7 for authorised share capital changes and e-form MGT-14 for resolutions approving issuance of shares, tracking statutory 30-day clocks from the relevant resolutions.",
    parties: ["Company", "Founders"],
    comments: "Company to provide uploaded e-forms and payment challans, and ensure RoC approval for authorised share capital increase.",
    status: "Not Started",
    priority: "Critical",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "SH-7, MGT-14, challans and RoC approval evidence" },
    riskCategory: "Regulatory filing risk",
    dependencies: [{ taskId: "cp-egm-approval", label: "EGM approvals before SH-7 / MGT-14" }],
    owner: "Company CS",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row B8; legal update L4 in PLAN.md",
    documentCategory: "RoC Filings",
    documentStatus: "Not Started",
    filing: { form: "MGT-14", deadline: "Prior to X", authority: "RoC", statutoryDays: 30, statutoryTrigger: "Resolution", statutoryNote: "MGT-14 / SH-7 statutory clock runs from the relevant resolution date." },
    statutoryDeadlineNote: "30 days from relevant resolution",
    mandatoryForClosing: true
  },
  {
    id: "cp-transaction-docs-execution",
    serialNumber: "B9",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Execute Subscription Agreement, Shareholders' Agreement, disclosure letter and all related ancillary agreements.",
    parties: ["Parties to Transaction Documents"],
    comments: "Documents to be stamped prior to execution.",
    status: "Not Started",
    priority: "Critical",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Executed transaction documents" },
    riskCategory: "Closing blocker",
    dependencies: [
      { taskId: "pre-stamp-papers", label: "Stamp papers procured before execution" },
      { taskId: "pre-transaction-documents", label: "Transaction documents in agreed form before execution" }
    ],
    owner: "Deal Associate",
    reviewer: "Partner",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row B9",
    documentCategory: "Transaction Documents",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "cp-employment-agreements",
    serialNumber: "B10",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Execute employment agreements with key employees, including Founders and employees identified by Investor.",
    parties: ["Company", "Founders", "Key Employees"],
    comments: "FIRM to provide draft.",
    status: "Not Started",
    priority: "High",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Executed employment agreements" },
    riskCategory: "Founder/company execution risk",
    dependencies: [],
    owner: "Company HR",
    reviewer: "Investor Counsel",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row B10",
    documentCategory: "Employment Agreements",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "cp-pas4-pas5",
    serialNumber: "B11",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "After MGT-14 filing, maintain private placement record in Form PAS-5 and circulate Form PAS-4 offer letter and serially numbered application form.",
    parties: ["Company", "Founders", "FIRM"],
    comments: "FIRM to provide templates. Draft PAS-5 and offer letter to be circulated for review, then executed copies to be provided to Investor. PAS-5 is maintained as a record and is not filed with RoC.",
    status: "Not Started",
    priority: "Critical",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "PAS-5 record and PAS-4 offer letter/application form" },
    riskCategory: "Regulatory filing risk",
    dependencies: [{ taskId: "cp-sh7-mgt14", label: "MGT-14 filed before PAS-4 / PAS-5 circulation" }],
    owner: "Company CS",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row B11; legal update L5 in PLAN.md",
    documentCategory: "Private Placement Forms",
    documentStatus: "Not Started",
    filing: { form: "PAS-4", deadline: "Prior to X", authority: "Internal", statutoryTrigger: "Internal", statutoryNote: "PAS-5 is a maintained record, not an RoC filing." },
    mandatoryForClosing: true
  },
  {
    id: "cp-agreed-form-documents",
    serialNumber: "B12",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Put amended articles, Form FC-GPR, e-form PAS-3 and closing resolutions in agreed form.",
    parties: ["Company", "Investor", "FIRM"],
    comments: "Drafts of amended articles, FC-GPR, PAS-3 and closing resolutions to be provided for Investor review.",
    status: "Not Started",
    priority: "Critical",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Agreed-form articles, FC-GPR, PAS-3 and closing resolutions" },
    riskCategory: "Closing blocker",
    dependencies: [
      { taskId: "pre-transaction-documents", label: "SHA terms feed restated articles" },
      { taskId: "cp-sh7-mgt14", label: "Filing context supports private placement forms" }
    ],
    owner: "Deal Associate",
    reviewer: "Partner",
    lastUpdated: now,
    notes: "Restated Articles tracked as agreed-form before closing and adoption at closing.",
    sourceReference: "Master Checklist row B12",
    documentCategory: "Articles",
    documentStatus: "Not Started",
    agreedFormRequired: true,
    mandatoryForClosing: true
  },
  {
    id: "cp-startup-india",
    serialNumber: "B13",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Apply for recognition as a startup under the Startup India Scheme.",
    parties: ["Company", "Founders"],
    comments: "-",
    status: "Not Started",
    priority: "Medium",
    blocker: false,
    evidence: { required: true, satisfied: false, label: "Startup India application acknowledgement" },
    riskCategory: "Pure admin",
    dependencies: [],
    owner: "Company Finance",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row B13",
    documentCategory: "Post-closing Evidence",
    documentStatus: "Not Started"
  },
  {
    id: "cp-fulfilment-certificate",
    serialNumber: "B14",
    phase: "Conditions Precedent",
    timeline: "Prior to X",
    action: "Issue CP fulfilment certificate in prescribed format for processing funding instructions, with necessary documentary evidence.",
    parties: ["Company", "Founders"],
    comments: "Format to be shared as part of the Subscription Agreement.",
    status: "Not Started",
    priority: "Critical",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Signed CP fulfilment certificate and evidence pack" },
    riskCategory: "Closing blocker",
    dependencies: [
      { taskId: "cp-valuation-certificate", label: "Critical CP evidence included" },
      { taskId: "cp-transaction-docs-execution", label: "Transaction documents execution confirmed" },
      { taskId: "cp-pas4-pas5", label: "Private placement process evidence included" }
    ],
    owner: "Company Counsel",
    reviewer: "Partner",
    lastUpdated: now,
    notes: "Requires documentary evidence.",
    sourceReference: "Master Checklist row B14",
    documentCategory: "CP Certificate",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "closing-investor-remittance",
    serialNumber: "C1",
    phase: "Closing Actions",
    timeline: "X",
    action: "Investor transfers subscription amount to Company's designated bank account through banking channels and furnishes MT 103 / UTR remittance details.",
    parties: ["Investor", "Company"],
    comments: "-",
    status: "Not Started",
    priority: "Critical",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "MT 103 / UTR and bank credit evidence" },
    riskCategory: "Closing blocker",
    dependencies: [{ taskId: "cp-fulfilment-certificate", label: "CP fulfilment before funding instruction" }],
    owner: "Investor Counsel",
    reviewer: "Partner",
    lastUpdated: now,
    notes: "Closing actions are simultaneous or interdependent. Track private placement banking-channel controls and separate-bank-account status where applicable.",
    sourceReference: "Master Checklist row C1; legal update L3 in PLAN.md",
    documentCategory: "Post-closing Evidence",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "closing-board-notice",
    serialNumber: "C2",
    phase: "Closing Actions",
    timeline: "X",
    action: "Issue board meeting notice for allotment, statutory filings, register updates, restated articles approval, nominee director / observer appointment, EGM call and closing acts.",
    parties: ["Company", "Founders", "FIRM"],
    comments: "FIRM to provide templates. Draft board resolution extracts to be circulated for review.",
    status: "Not Started",
    priority: "High",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Closing BM notice and draft resolutions" },
    riskCategory: "Legal validity risk",
    dependencies: [{ taskId: "cp-agreed-form-documents", label: "Closing resolutions in agreed form" }],
    owner: "Company CS",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row C2",
    documentCategory: "Closing Resolutions",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "closing-board-approval",
    serialNumber: "C3",
    phase: "Closing Actions",
    timeline: "X",
    action: "Hold board meeting for approval of the items in C2, including allotment of subscription shares and confirmation that allotment/refund timing controls are satisfied.",
    parties: ["Company", "Founders"],
    comments: "Certified copies of register of members and register of directors also to be shared.",
    status: "Not Started",
    priority: "Critical",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Executed closing board resolutions and register extracts" },
    riskCategory: "Closing blocker",
    dependencies: [
      { taskId: "closing-investor-remittance", label: "Investor remittance before allotment" },
      { taskId: "closing-board-notice", label: "Board notice precedes closing board approval" }
    ],
    owner: "Company CS",
    reviewer: "Partner",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row C3; legal update L3 in PLAN.md",
    documentCategory: "Closing Resolutions",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "closing-egm-notice",
    serialNumber: "C4",
    phase: "Closing Actions",
    timeline: "X",
    action: "Issue EGM notice for adoption of amended/restated articles, entrenchment provisions and nominee director appointment.",
    parties: ["Company", "Founders", "FIRM"],
    comments: "Draft notice of EGM to be circulated by Company. Resolutions should contain specific SHA provisions flagged for this purpose.",
    status: "Not Started",
    priority: "High",
    blocker: true,
    evidence: { required: true, satisfied: false, label: "Closing EGM notice and shareholder resolutions" },
    riskCategory: "Legal validity risk",
    dependencies: [{ taskId: "cp-agreed-form-documents", label: "Restated articles agreed before adoption" }],
    owner: "Company CS",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row C4",
    documentCategory: "Articles",
    documentStatus: "Not Started",
    mandatoryForClosing: true
  },
  {
    id: "closing-share-certificates",
    serialNumber: "C5",
    phase: "Closing Actions",
    timeline: "X",
    action: "Deliver duly stamped, sealed and signed share certificates to Investor, tracking the 30-day issue window and state-specific stamp duty.",
    parties: ["Company", "Founders"],
    comments: "Draft to be shared by Company for review. Track state-specific stamping on certificates.",
    status: "Not Started",
    priority: "High",
    blocker: false,
    evidence: { required: true, satisfied: false, label: "Signed share certificates" },
    riskCategory: "Investor protection risk",
    dependencies: [{ taskId: "closing-board-approval", label: "Allotment approval before share certificate delivery" }],
    owner: "Company CS",
    reviewer: "Investor Counsel",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row C5; legal update L7 in PLAN.md",
    documentCategory: "Share Certificates",
    documentStatus: "Not Started",
    statutoryDeadlineNote: "30 days from allotment"
  },
  {
    id: "closing-management-rights-letter",
    serialNumber: "C6",
    phase: "Closing Actions",
    timeline: "X",
    action: "Issue Management Rights Letter to Investor in prescribed format.",
    parties: ["Company", "Founders"],
    comments: "Format will be annexed to the Subscription Agreement.",
    status: "Not Started",
    priority: "Medium",
    blocker: false,
    evidence: { required: true, satisfied: false, label: "Issued Management Rights Letter" },
    riskCategory: "Investor protection risk",
    dependencies: [{ taskId: "cp-transaction-docs-execution", label: "Subscription Agreement includes prescribed format" }],
    owner: "Company Counsel",
    reviewer: "Investor Counsel",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row C6",
    documentCategory: "Management Rights Letter",
    documentStatus: "Not Started"
  },
  {
    id: "post-pas-3",
    serialNumber: "D1",
    phase: "Post-Closing Actions",
    timeline: "X+10",
    action: "File e-form PAS-3 for allotment of shares to Investor.",
    parties: ["Company", "Founders"],
    comments: "Internal target is X+10. Statutory hard limit should be tracked as 15 days from allotment. Company may use the funds only once PAS-3 is filed. Company to share e-form and challan.",
    status: "Not Started",
    priority: "Critical",
    blocker: false,
    evidence: { required: true, satisfied: false, label: "Filed PAS-3 and challan" },
    riskCategory: "Regulatory filing risk",
    dependencies: [{ taskId: "closing-board-approval", label: "Allotment before PAS-3" }],
    owner: "Company CS",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row D1; legal update L1 in PLAN.md",
    documentCategory: "RoC Filings",
    documentStatus: "Not Started",
    filing: { form: "PAS-3", deadline: "X+10", authority: "RoC", statutoryDays: 15, statutoryTrigger: "Allotment", statutoryNote: "Private placement PAS-3 hard limit: 15 days from allotment. Funds use blocked until filed." },
    statutoryDeadlineNote: "15 days from allotment"
  },
  {
    id: "post-mgt14-closing",
    serialNumber: "D2",
    phase: "Post-Closing Actions",
    timeline: "X+30",
    action: "File MGT-14 for special/unanimous resolutions for amended articles and entrenchment.",
    parties: ["Company", "Founders"],
    comments: "Company to provide uploaded e-form and payment challan. Statutory clock runs 30 days from the relevant resolution.",
    status: "Not Started",
    priority: "High",
    blocker: false,
    evidence: { required: true, satisfied: false, label: "Filed MGT-14 and challan" },
    riskCategory: "Regulatory filing risk",
    dependencies: [{ taskId: "closing-egm-notice", label: "Closing shareholder approvals before MGT-14 / DIR-12" }],
    owner: "Company CS",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row D2; legal update L4 in PLAN.md",
    documentCategory: "RoC Filings",
    documentStatus: "Not Started",
    filing: { form: "MGT-14", deadline: "X+30", authority: "RoC", statutoryDays: 30, statutoryTrigger: "Resolution", statutoryNote: "MGT-14 statutory clock runs from the relevant special/unanimous resolution." },
    statutoryDeadlineNote: "30 days from relevant resolution"
  },
  {
    id: "post-dir-12",
    serialNumber: "D3",
    phase: "Post-Closing Actions",
    timeline: "X+30",
    action: "File DIR-12 for Investor nominee director appointment, if applicable.",
    parties: ["Company", "Founders"],
    comments: "Company to provide uploaded e-form and payment challan. Mark Not Applicable if no nominee director appointment is made.",
    status: "Not Started",
    priority: "High",
    blocker: false,
    evidence: { required: true, satisfied: false, label: "Filed DIR-12 and challan, or N/A confirmation" },
    riskCategory: "Regulatory filing risk",
    dependencies: [{ taskId: "closing-egm-notice", label: "Closing shareholder approvals before DIR-12" }],
    owner: "Company CS",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row D2 (DIR-12 split into its own post-closing task); confirm DIR-12 mechanics with counsel",
    documentCategory: "RoC Filings",
    documentStatus: "Not Started",
    filing: { form: "DIR-12", deadline: "X+30", authority: "RoC", statutoryDays: 30, statutoryTrigger: "Resolution", statutoryNote: "DIR-12 statutory clock should be confirmed against the appointment date/resolution mechanics." },
    statutoryDeadlineNote: "30 days from appointment/resolution"
  },
  {
    id: "post-fc-gpr",
    serialNumber: "D4",
    phase: "Post-Closing Actions",
    timeline: "X+30",
    action: "File Form FC-GPR and all supporting documents for effective FEMA filing.",
    parties: ["Company", "Founders", "Investor"],
    comments: "FC-GPR is filed through SMF on the RBI FIRMS portal within 30 days of allotment. Confirm Entity Master Form registration and track Late Submission Fee risk if delayed.",
    status: "Not Started",
    priority: "Critical",
    blocker: false,
    evidence: { required: true, satisfied: false, label: "Filed FC-GPR / SMF acknowledgement, EMF confirmation and supporting pack register link" },
    riskCategory: "Regulatory filing risk",
    dependencies: [
      { taskId: "closing-investor-remittance", label: "Closing remittance before FC-GPR" },
      { taskId: "post-pas-3", label: "Allotment filing evidence supports FC-GPR pack" }
    ],
    owner: "Company Finance",
    reviewer: "Investor Counsel",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row D3; legal update L6 in PLAN.md",
    documentCategory: "FEMA Filings",
    documentStatus: "Not Started",
    filing: { form: "FC-GPR", deadline: "X+30", authority: "RBI/FIRMS", statutoryDays: 30, statutoryTrigger: "Allotment", statutoryNote: "FC-GPR via SMF on FIRMS within 30 days of allotment; EMF should be registered; late filing may attract LSF." },
    statutoryDeadlineNote: "30 days from allotment"
  },
  {
    id: "post-esop-scheme",
    serialNumber: "D5",
    phase: "Post-Closing Actions",
    timeline: "X+60",
    action: "Adopt employee stock option scheme in accordance with the Shareholders' Agreement.",
    parties: ["Company"],
    comments: "-",
    status: "Not Started",
    priority: "Medium",
    blocker: false,
    evidence: { required: true, satisfied: false, label: "Adopted ESOP scheme and approvals" },
    riskCategory: "Founder/company execution risk",
    dependencies: [{ taskId: "cp-transaction-docs-execution", label: "SHA terms govern ESOP adoption" }],
    owner: "Company Legal",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row D4",
    documentCategory: "Post-closing Evidence",
    documentStatus: "Not Started"
  },
  {
    id: "post-accounting-firm",
    serialNumber: "D6",
    phase: "Post-Closing Actions",
    timeline: "X+90",
    action: "Appoint statutory and internal accounting firm in accordance with the Shareholders' Agreement.",
    parties: ["Company"],
    comments: "-",
    status: "Not Started",
    priority: "Medium",
    blocker: false,
    evidence: { required: true, satisfied: false, label: "Accounting firm appointment evidence" },
    riskCategory: "Pure admin",
    dependencies: [{ taskId: "cp-transaction-docs-execution", label: "SHA terms govern appointment" }],
    owner: "Company Finance",
    reviewer: "Deal Associate",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row D5",
    documentCategory: "Post-closing Evidence",
    documentStatus: "Not Started"
  },
  {
    id: "post-do-insurance",
    serialNumber: "D7",
    phase: "Post-Closing Actions",
    timeline: "X+90",
    action: "Obtain directors' and officers' liability insurance for Investor's nominee director in accordance with the Shareholders' Agreement.",
    parties: ["Company"],
    comments: "-",
    status: "Not Started",
    priority: "Medium",
    blocker: false,
    evidence: { required: true, satisfied: false, label: "D&O insurance policy / binder" },
    riskCategory: "Investor protection risk",
    dependencies: [{ taskId: "cp-transaction-docs-execution", label: "SHA terms govern D&O insurance" }],
    owner: "Company Finance",
    reviewer: "Investor Counsel",
    lastUpdated: now,
    notes: "",
    sourceReference: "Master Checklist row D6",
    documentCategory: "Post-closing Evidence",
    documentStatus: "Not Started"
  }
];

export const seedNotes: DealNote[] = [
  {
    id: "note-1",
    category: "Open Question",
    text: "Confirm whether DIR-12 is applicable based on the final nominee director appointment mechanics.",
    createdAt: now
  },
  {
    id: "note-2",
    category: "Waiver Position",
    text: "No CP waiver to be assumed unless expressly approved in writing and reflected in the closing pack.",
    createdAt: now
  }
];

export const seedDeal: Deal = {
  id: "deal-seed-financing",
  name: "Seed Financing Closing",
  companyName: "Insert Name of Investee Company",
  investorName: "Lead Investor",
  closingDateX: "",
  firmLabel: "FIRM",
  tasks: seedTasks,
  notes: seedNotes
};

export function createSeedDeal(): Deal {
  return {
    ...seedDeal,
    tasks: seedTasks.map((task) => ({
      ...task,
      dependencies: task.dependencies.map((dependency) => ({ ...dependency })),
      evidence: { ...task.evidence }
    })),
    notes: seedNotes.map((note) => ({ ...note }))
  };
}
