-- GENERATED FILE - do not edit by hand.
-- Source: lib/checklistSeed.ts via scripts/generateTemplateSeed.ts
-- Regenerate with: npx tsx scripts/generateTemplateSeed.ts
--
-- Apply with a privileged connection (Supabase SQL editor / service role):
-- RLS blocks clients from writing a global (null-org) seed template.
-- Run db/schema.sql first; this seed is idempotent (re-running replaces the
-- existing global seed of the same name + version).

begin;

delete from template
where organization_id is null
  and name = 'India Seed Financing - Private Placement'
  and version = 1;

insert into template (id, organization_id, name, version, jurisdiction, is_seed)
values ('00000000-0000-4000-8000-000000000001', null, 'India Seed Financing - Private Placement', 1, 'IN', true);

insert into template_task (
  template_id,
  organization_id,
  source_task_id,
  serial_number,
  phase,
  timeline,
  action,
  parties,
  comments,
  priority,
  blocker,
  evidence,
  risk_category,
  owner_label,
  reviewer_label,
  source_reference,
  document_category,
  document_status,
  filing,
  statutory_deadline_note,
  agreed_form_required,
  mandatory_for_closing
)
values
  ('00000000-0000-4000-8000-000000000001', null, 'pre-transaction-documents', 'A1', 'Pre-Execution Items', 'Prior to X', 'Transaction documents to be finalised, including Shareholders'' Agreement, Subscription Agreement, Employment Agreement and ancillary documents.', '["Company","Founders","FIRM","Investor"]'::jsonb, '-', 'Critical', false, '{"required":true,"satisfied":false,"label":"Agreed-form transaction documents"}'::jsonb, 'Closing blocker', 'Deal Associate', 'Partner', 'Master Checklist row A1', 'Transaction Documents', 'Not Started', null, null, true, true),
  ('00000000-0000-4000-8000-000000000001', null, 'pre-stamp-papers', 'A2', 'Pre-Execution Items', 'Prior to X', 'Stamp papers to be procured before execution.', '["Company","FIRM"]'::jsonb, 'FIRM will provide relevant stamp duty procurement details closer to execution.', 'High', false, '{"required":true,"satisfied":false,"label":"Stamp paper procurement proof"}'::jsonb, 'Legal validity risk', 'Company CS', 'Deal Associate', 'Master Checklist row A2', 'Transaction Documents', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'pre-disclosure-letter', 'A3', 'Pre-Execution Items', 'Prior to X', 'Disclosure letter to be finalised.', '["Company","Founders","FIRM"]'::jsonb, 'To be circulated by Company for FIRM review.', 'High', false, '{"required":true,"satisfied":false,"label":"Final disclosure letter"}'::jsonb, 'Investor protection risk', 'Company Counsel', 'Investor Counsel', 'Master Checklist row A3', 'Transaction Documents', 'Not Started', null, null, true, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-due-diligence', 'B1', 'Conditions Precedent', 'Prior to X', 'Completion of financial, business and legal due diligence, management background and reference checks, and resolution of diligence issues.', '["Company","Founders","Investor","FIRM"]'::jsonb, '-', 'High', false, '{"required":true,"satisfied":false,"label":"Diligence closure tracker / issue resolution evidence"}'::jsonb, 'Investor protection risk', 'Diligence Lead', 'Partner', 'Master Checklist row B1', 'Post-closing Evidence', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-third-party-consents', 'B2', 'Conditions Precedent', 'Prior to X', 'Obtain third-party consents required for the fundraise and related transactions, if applicable.', '["Company","Founders"]'::jsonb, '-', 'Medium', false, '{"required":true,"satisfied":false,"label":"Third-party consent copies or N/A confirmation"}'::jsonb, 'Legal validity risk', 'Company Legal', 'Deal Associate', 'Master Checklist row B2', 'Corporate Approvals', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-valuation-certificate', 'B3', 'Conditions Precedent', 'Prior to X', 'Procure valuation support for the issue price, including Registered Valuer report for Companies Act preferential allotment and FEMA pricing certificate from CA / merchant banker / cost accountant, as applicable.', '["Registered Valuer","Independent CA / Merchant Banker","Company","FIRM"]'::jsonb, 'Company to share draft valuation materials with FIRM for review and then provide signed versions. Report should be dated 30 days prior to EGM for issuance approval. Income-tax angel-tax analysis should be treated as legacy/DD context and confirmed for current applicability.', 'Critical', false, '{"required":true,"satisfied":false,"label":"Signed valuation report / FEMA pricing certificate register link"}'::jsonb, 'Closing blocker', 'Company Finance', 'Partner', 'Master Checklist row B3; legal update L2/L8 in PLAN.md', 'Valuation', 'Not Started', null, 'Soft freshness check before EGM', false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-board-notice-issuance', 'B4', 'Conditions Precedent', 'Prior to X', 'Issue notice of board meeting for transaction document approval, bank account, ESOP pool, capital changes, consents, private placement offer approval and EGM call.', '["Company","Founders","FIRM"]'::jsonb, 'FIRM to provide templates. Company to circulate draft board resolution extracts for review and share executed copies once confirmed.', 'High', false, '{"required":true,"satisfied":false,"label":"Board notice and draft resolutions"}'::jsonb, 'Legal validity risk', 'Company CS', 'Deal Associate', 'Master Checklist row B4', 'Corporate Approvals', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-board-approval', 'B5', 'Conditions Precedent', 'Prior to X', 'Hold board meeting for approval of the items in B4.', '["Company","Founders"]'::jsonb, '-', 'Critical', false, '{"required":true,"satisfied":false,"label":"Executed board resolution extracts"}'::jsonb, 'Closing blocker', 'Company CS', 'Partner', 'Master Checklist row B5', 'Corporate Approvals', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-egm-notice', 'B6', 'Conditions Precedent', 'Prior to X', 'Issue EGM notice for increase/reclassification of authorised share capital and private placement issuance approval.', '["Company","Founders","FIRM"]'::jsonb, 'FIRM to provide templates. Draft EGM notice to be circulated by Company for review.', 'High', false, '{"required":true,"satisfied":false,"label":"EGM notice and draft shareholder resolutions"}'::jsonb, 'Legal validity risk', 'Company CS', 'Deal Associate', 'Master Checklist row B6', 'Corporate Approvals', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-egm-approval', 'B7', 'Conditions Precedent', 'Prior to X', 'Hold EGM for approval of the items in B6.', '["Company","Founders"]'::jsonb, '-', 'Critical', false, '{"required":true,"satisfied":false,"label":"Executed EGM resolution extracts"}'::jsonb, 'Closing blocker', 'Company CS', 'Partner', 'Master Checklist row B7', 'Corporate Approvals', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-sh7-mgt14', 'B8', 'Conditions Precedent', 'Prior to X', 'File e-form SH-7 for authorised share capital changes and e-form MGT-14 for resolutions approving issuance of shares, tracking statutory 30-day clocks from the relevant resolutions.', '["Company","Founders"]'::jsonb, 'Company to provide uploaded e-forms and payment challans, and ensure RoC approval for authorised share capital increase.', 'Critical', false, '{"required":true,"satisfied":false,"label":"SH-7, MGT-14, challans and RoC approval evidence"}'::jsonb, 'Regulatory filing risk', 'Company CS', 'Deal Associate', 'Master Checklist row B8; legal update L4 in PLAN.md', 'RoC Filings', 'Not Started', '{"form":"MGT-14","deadline":"Prior to X","authority":"RoC","statutoryDays":30,"statutoryTrigger":"Resolution","statutoryNote":"MGT-14 / SH-7 statutory clock runs from the relevant resolution date."}'::jsonb, '30 days from relevant resolution', false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-transaction-docs-execution', 'B9', 'Conditions Precedent', 'Prior to X', 'Execute Subscription Agreement, Shareholders'' Agreement, disclosure letter and all related ancillary agreements.', '["Parties to Transaction Documents"]'::jsonb, 'Documents to be stamped prior to execution.', 'Critical', false, '{"required":true,"satisfied":false,"label":"Executed transaction documents"}'::jsonb, 'Closing blocker', 'Deal Associate', 'Partner', 'Master Checklist row B9', 'Transaction Documents', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-employment-agreements', 'B10', 'Conditions Precedent', 'Prior to X', 'Execute employment agreements with key employees, including Founders and employees identified by Investor.', '["Company","Founders","Key Employees"]'::jsonb, 'FIRM to provide draft.', 'High', false, '{"required":true,"satisfied":false,"label":"Executed employment agreements"}'::jsonb, 'Founder/company execution risk', 'Company HR', 'Investor Counsel', 'Master Checklist row B10', 'Employment Agreements', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-pas4-pas5', 'B11', 'Conditions Precedent', 'Prior to X', 'After MGT-14 filing, maintain private placement record in Form PAS-5 and circulate Form PAS-4 offer letter and serially numbered application form.', '["Company","Founders","FIRM"]'::jsonb, 'FIRM to provide templates. Draft PAS-5 and offer letter to be circulated for review, then executed copies to be provided to Investor. PAS-5 is maintained as a record and is not filed with RoC.', 'Critical', false, '{"required":true,"satisfied":false,"label":"PAS-5 record and PAS-4 offer letter/application form"}'::jsonb, 'Regulatory filing risk', 'Company CS', 'Deal Associate', 'Master Checklist row B11; legal update L5 in PLAN.md', 'Private Placement Forms', 'Not Started', '{"form":"PAS-4","deadline":"Prior to X","authority":"Internal","statutoryTrigger":"Internal","statutoryNote":"PAS-5 is a maintained record, not an RoC filing."}'::jsonb, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-agreed-form-documents', 'B12', 'Conditions Precedent', 'Prior to X', 'Put amended articles, Form FC-GPR, e-form PAS-3 and closing resolutions in agreed form.', '["Company","Investor","FIRM"]'::jsonb, 'Drafts of amended articles, FC-GPR, PAS-3 and closing resolutions to be provided for Investor review.', 'Critical', false, '{"required":true,"satisfied":false,"label":"Agreed-form articles, FC-GPR, PAS-3 and closing resolutions"}'::jsonb, 'Closing blocker', 'Deal Associate', 'Partner', 'Master Checklist row B12', 'Articles', 'Not Started', null, null, true, true),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-startup-india', 'B13', 'Conditions Precedent', 'Prior to X', 'Apply for recognition as a startup under the Startup India Scheme.', '["Company","Founders"]'::jsonb, '-', 'Medium', false, '{"required":true,"satisfied":false,"label":"Startup India application acknowledgement"}'::jsonb, 'Pure admin', 'Company Finance', 'Deal Associate', 'Master Checklist row B13', 'Post-closing Evidence', 'Not Started', null, null, false, false),
  ('00000000-0000-4000-8000-000000000001', null, 'cp-fulfilment-certificate', 'B14', 'Conditions Precedent', 'Prior to X', 'Issue CP fulfilment certificate in prescribed format for processing funding instructions, with necessary documentary evidence.', '["Company","Founders"]'::jsonb, 'Format to be shared as part of the Subscription Agreement.', 'Critical', false, '{"required":true,"satisfied":false,"label":"Signed CP fulfilment certificate and evidence pack"}'::jsonb, 'Closing blocker', 'Company Counsel', 'Partner', 'Master Checklist row B14', 'CP Certificate', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'closing-investor-remittance', 'C1', 'Closing Actions', 'X', 'Investor transfers subscription amount to Company''s designated bank account through banking channels and furnishes MT 103 / UTR remittance details.', '["Investor","Company"]'::jsonb, '-', 'Critical', false, '{"required":true,"satisfied":false,"label":"MT 103 / UTR and bank credit evidence"}'::jsonb, 'Closing blocker', 'Investor Counsel', 'Partner', 'Master Checklist row C1; legal update L3 in PLAN.md', 'Post-closing Evidence', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'closing-board-notice', 'C2', 'Closing Actions', 'X', 'Issue board meeting notice for allotment, statutory filings, register updates, restated articles approval, nominee director / observer appointment, EGM call and closing acts.', '["Company","Founders","FIRM"]'::jsonb, 'FIRM to provide templates. Draft board resolution extracts to be circulated for review.', 'High', false, '{"required":true,"satisfied":false,"label":"Closing BM notice and draft resolutions"}'::jsonb, 'Legal validity risk', 'Company CS', 'Deal Associate', 'Master Checklist row C2', 'Closing Resolutions', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'closing-board-approval', 'C3', 'Closing Actions', 'X', 'Hold board meeting for approval of the items in C2, including allotment of subscription shares and confirmation that allotment/refund timing controls are satisfied.', '["Company","Founders"]'::jsonb, 'Certified copies of register of members and register of directors also to be shared.', 'Critical', false, '{"required":true,"satisfied":false,"label":"Executed closing board resolutions and register extracts"}'::jsonb, 'Closing blocker', 'Company CS', 'Partner', 'Master Checklist row C3; legal update L3 in PLAN.md', 'Closing Resolutions', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'closing-egm-notice', 'C4', 'Closing Actions', 'X', 'Issue EGM notice for adoption of amended/restated articles, entrenchment provisions and nominee director appointment.', '["Company","Founders","FIRM"]'::jsonb, 'Draft notice of EGM to be circulated by Company. Resolutions should contain specific SHA provisions flagged for this purpose.', 'High', false, '{"required":true,"satisfied":false,"label":"Closing EGM notice and shareholder resolutions"}'::jsonb, 'Legal validity risk', 'Company CS', 'Deal Associate', 'Master Checklist row C4', 'Articles', 'Not Started', null, null, false, true),
  ('00000000-0000-4000-8000-000000000001', null, 'closing-share-certificates', 'C5', 'Closing Actions', 'X', 'Deliver duly stamped, sealed and signed share certificates to Investor, tracking the 30-day issue window and state-specific stamp duty.', '["Company","Founders"]'::jsonb, 'Draft to be shared by Company for review. Track state-specific stamping on certificates.', 'High', false, '{"required":true,"satisfied":false,"label":"Signed share certificates"}'::jsonb, 'Investor protection risk', 'Company CS', 'Investor Counsel', 'Master Checklist row C5; legal update L7 in PLAN.md', 'Share Certificates', 'Not Started', null, '30 days from allotment', false, false),
  ('00000000-0000-4000-8000-000000000001', null, 'closing-management-rights-letter', 'C6', 'Closing Actions', 'X', 'Issue Management Rights Letter to Investor in prescribed format.', '["Company","Founders"]'::jsonb, 'Format will be annexed to the Subscription Agreement.', 'Medium', false, '{"required":true,"satisfied":false,"label":"Issued Management Rights Letter"}'::jsonb, 'Investor protection risk', 'Company Counsel', 'Investor Counsel', 'Master Checklist row C6', 'Management Rights Letter', 'Not Started', null, null, false, false),
  ('00000000-0000-4000-8000-000000000001', null, 'post-pas-3', 'D1', 'Post-Closing Actions', 'X+10', 'File e-form PAS-3 for allotment of shares to Investor.', '["Company","Founders"]'::jsonb, 'Internal target is X+10. Statutory hard limit should be tracked as 15 days from allotment. Company may use the funds only once PAS-3 is filed. Company to share e-form and challan.', 'Critical', false, '{"required":true,"satisfied":false,"label":"Filed PAS-3 and challan"}'::jsonb, 'Regulatory filing risk', 'Company CS', 'Deal Associate', 'Master Checklist row D1; legal update L1 in PLAN.md', 'RoC Filings', 'Not Started', '{"form":"PAS-3","deadline":"X+10","authority":"RoC","statutoryDays":15,"statutoryTrigger":"Allotment","statutoryNote":"Private placement PAS-3 hard limit: 15 days from allotment. Funds use blocked until filed."}'::jsonb, '15 days from allotment', false, false),
  ('00000000-0000-4000-8000-000000000001', null, 'post-mgt14-closing', 'D2', 'Post-Closing Actions', 'X+30', 'File MGT-14 for special/unanimous resolutions for amended articles and entrenchment.', '["Company","Founders"]'::jsonb, 'Company to provide uploaded e-form and payment challan. Statutory clock runs 30 days from the relevant resolution.', 'High', false, '{"required":true,"satisfied":false,"label":"Filed MGT-14 and challan"}'::jsonb, 'Regulatory filing risk', 'Company CS', 'Deal Associate', 'Master Checklist row D2; legal update L4 in PLAN.md', 'RoC Filings', 'Not Started', '{"form":"MGT-14","deadline":"X+30","authority":"RoC","statutoryDays":30,"statutoryTrigger":"Resolution","statutoryNote":"MGT-14 statutory clock runs from the relevant special/unanimous resolution."}'::jsonb, '30 days from relevant resolution', false, false),
  ('00000000-0000-4000-8000-000000000001', null, 'post-dir-12', 'D3', 'Post-Closing Actions', 'X+30', 'File DIR-12 for Investor nominee director appointment, if applicable.', '["Company","Founders"]'::jsonb, 'Company to provide uploaded e-form and payment challan. Mark Not Applicable if no nominee director appointment is made.', 'High', false, '{"required":true,"satisfied":false,"label":"Filed DIR-12 and challan, or N/A confirmation"}'::jsonb, 'Regulatory filing risk', 'Company CS', 'Deal Associate', 'Master Checklist row D2 (DIR-12 split into its own post-closing task); confirm DIR-12 mechanics with counsel', 'RoC Filings', 'Not Started', '{"form":"DIR-12","deadline":"X+30","authority":"RoC","statutoryDays":30,"statutoryTrigger":"Resolution","statutoryNote":"DIR-12 statutory clock should be confirmed against the appointment date/resolution mechanics."}'::jsonb, '30 days from appointment/resolution', false, false),
  ('00000000-0000-4000-8000-000000000001', null, 'post-fc-gpr', 'D4', 'Post-Closing Actions', 'X+30', 'File Form FC-GPR and all supporting documents for effective FEMA filing.', '["Company","Founders","Investor"]'::jsonb, 'FC-GPR is filed through SMF on the RBI FIRMS portal within 30 days of allotment. Confirm Entity Master Form registration and track Late Submission Fee risk if delayed.', 'Critical', false, '{"required":true,"satisfied":false,"label":"Filed FC-GPR / SMF acknowledgement, EMF confirmation and supporting pack register link"}'::jsonb, 'Regulatory filing risk', 'Company Finance', 'Investor Counsel', 'Master Checklist row D3; legal update L6 in PLAN.md', 'FEMA Filings', 'Not Started', '{"form":"FC-GPR","deadline":"X+30","authority":"RBI/FIRMS","statutoryDays":30,"statutoryTrigger":"Allotment","statutoryNote":"FC-GPR via SMF on FIRMS within 30 days of allotment; EMF should be registered; late filing may attract LSF."}'::jsonb, '30 days from allotment', false, false),
  ('00000000-0000-4000-8000-000000000001', null, 'post-esop-scheme', 'D5', 'Post-Closing Actions', 'X+60', 'Adopt employee stock option scheme in accordance with the Shareholders'' Agreement.', '["Company"]'::jsonb, '-', 'Medium', false, '{"required":true,"satisfied":false,"label":"Adopted ESOP scheme and approvals"}'::jsonb, 'Founder/company execution risk', 'Company Legal', 'Deal Associate', 'Master Checklist row D4', 'Post-closing Evidence', 'Not Started', null, null, false, false),
  ('00000000-0000-4000-8000-000000000001', null, 'post-accounting-firm', 'D6', 'Post-Closing Actions', 'X+90', 'Appoint statutory and internal accounting firm in accordance with the Shareholders'' Agreement.', '["Company"]'::jsonb, '-', 'Medium', false, '{"required":true,"satisfied":false,"label":"Accounting firm appointment evidence"}'::jsonb, 'Pure admin', 'Company Finance', 'Deal Associate', 'Master Checklist row D5', 'Post-closing Evidence', 'Not Started', null, null, false, false),
  ('00000000-0000-4000-8000-000000000001', null, 'post-do-insurance', 'D7', 'Post-Closing Actions', 'X+90', 'Obtain directors'' and officers'' liability insurance for Investor''s nominee director in accordance with the Shareholders'' Agreement.', '["Company"]'::jsonb, '-', 'Medium', false, '{"required":true,"satisfied":false,"label":"D&O insurance policy / binder"}'::jsonb, 'Investor protection risk', 'Company Finance', 'Investor Counsel', 'Master Checklist row D6', 'Post-closing Evidence', 'Not Started', null, null, false, false);

insert into template_dependency (template_id, organization_id, template_task_id, prerequisite_template_task_id, label)
select '00000000-0000-4000-8000-000000000001', null, child.id, prereq.id, d.label
from (values
  ('pre-stamp-papers', 'pre-transaction-documents', 'Documents must be near final before stamping'),
  ('pre-disclosure-letter', 'pre-transaction-documents', 'Disclosure letter tied to transaction documents'),
  ('cp-board-notice-issuance', 'cp-valuation-certificate', 'Valuation certificate supports issuance approval'),
  ('cp-board-approval', 'cp-board-notice-issuance', 'Board notice precedes board meeting'),
  ('cp-egm-notice', 'cp-board-approval', 'Board approval before EGM notice'),
  ('cp-egm-approval', 'cp-egm-notice', 'EGM notice precedes EGM'),
  ('cp-sh7-mgt14', 'cp-egm-approval', 'EGM approvals before SH-7 / MGT-14'),
  ('cp-transaction-docs-execution', 'pre-stamp-papers', 'Stamp papers procured before execution'),
  ('cp-transaction-docs-execution', 'pre-transaction-documents', 'Transaction documents in agreed form before execution'),
  ('cp-pas4-pas5', 'cp-sh7-mgt14', 'MGT-14 filed before PAS-4 / PAS-5 circulation'),
  ('cp-agreed-form-documents', 'pre-transaction-documents', 'SHA terms feed restated articles'),
  ('cp-agreed-form-documents', 'cp-sh7-mgt14', 'Filing context supports private placement forms'),
  ('cp-fulfilment-certificate', 'cp-valuation-certificate', 'Critical CP evidence included'),
  ('cp-fulfilment-certificate', 'cp-transaction-docs-execution', 'Transaction documents execution confirmed'),
  ('cp-fulfilment-certificate', 'cp-pas4-pas5', 'Private placement process evidence included'),
  ('closing-investor-remittance', 'cp-fulfilment-certificate', 'CP fulfilment before funding instruction'),
  ('closing-board-notice', 'cp-agreed-form-documents', 'Closing resolutions in agreed form'),
  ('closing-board-approval', 'closing-investor-remittance', 'Investor remittance before allotment'),
  ('closing-board-approval', 'closing-board-notice', 'Board notice precedes closing board approval'),
  ('closing-egm-notice', 'cp-agreed-form-documents', 'Restated articles agreed before adoption'),
  ('closing-share-certificates', 'closing-board-approval', 'Allotment approval before share certificate delivery'),
  ('closing-management-rights-letter', 'cp-transaction-docs-execution', 'Subscription Agreement includes prescribed format'),
  ('post-pas-3', 'closing-board-approval', 'Allotment before PAS-3'),
  ('post-mgt14-closing', 'closing-egm-notice', 'Closing shareholder approvals before MGT-14 / DIR-12'),
  ('post-dir-12', 'closing-egm-notice', 'Closing shareholder approvals before DIR-12'),
  ('post-fc-gpr', 'closing-investor-remittance', 'Closing remittance before FC-GPR'),
  ('post-fc-gpr', 'post-pas-3', 'Allotment filing evidence supports FC-GPR pack'),
  ('post-esop-scheme', 'cp-transaction-docs-execution', 'SHA terms govern ESOP adoption'),
  ('post-accounting-firm', 'cp-transaction-docs-execution', 'SHA terms govern appointment'),
  ('post-do-insurance', 'cp-transaction-docs-execution', 'SHA terms govern D&O insurance')
) as d(child_source, prereq_source, label)
join template_task child
  on child.template_id = '00000000-0000-4000-8000-000000000001' and child.source_task_id = d.child_source
join template_task prereq
  on prereq.template_id = '00000000-0000-4000-8000-000000000001' and prereq.source_task_id = d.prereq_source;

commit;
